### ISSUE TITLE
Interface not found error when using via Drupal

### ISSUE THREAD

**Issue by ediblesites** [giggsey/drupal-libphonenumber#1]
Throws "Fatal error: Interface 'libphonenumber\MetadataLoaderInterface' not found in /.../sites/all/libraries/libphonenumber-for-php/src/libphonenumber/DefaultMetadataLoader.php on line 7" when attempting to edit the field definitions under the content type

**Comment by giggsey** [comment]
Have a look at https://www.drupal.org/node/2365753

This repository was created in order to apply a fix for the issue.

Any further comments etc. should be reported against the actual drupal module instead.
